# Generated by Django 3.1.4 on 2021-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestation',
            name='gpa',
            field=models.FloatField(verbose_name='GPA:'),
        ),
    ]
